name: Validate changes

on:
  push:
    branches:
      - "**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 'latest'

    - name: Install dependencies with Bun
      run: bun install

    - name: Check for type errors using TSC
      run: bun run lint

    - name: Build package with Bun
      run: bun run build